name: build

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4.2.1
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'sbt'

      - name: Test
        env:
          CI_VERSION: ${{ github.ref }}
          SBT_OPTS: '-Xmx2G'
        run: sbt "; test"
