name: Scala CI

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*'
  release:
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
    - name: Run tests
      run: sbt test
